TRUNCATE weapons;

INSERT INTO weapons (
    id, 
    name, 
    image_url, 
    first_trait1,
    first_trait2,
    first_trait3,
    first_trait4,
    first_trait5,
    first_trait6,
    second_trait1,
    second_trait2,
    second_trait3,
    second_trait4,
    second_trait5,
    second_trait6,
    preferred_combo
    -- combo_description
    ) VALUES (
        1,
        'Calus Mini-Tool', 
        'https://ik.imagekit.io/kwroldan/Capstone/Calus_Mini_Tool_ceB-gCdmI.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654720693242', 
        'Unrelenting',  
        'Slideways',
        'Threat Detector',
        'Air Assault',
        'Moving Target',
        'Grave Robber',
        'Disruption Break',
        'Surrounded',
        'Feeding Frenzy',
        'Eye of the Storm',
        'Tap the Trigger',
        'Incadescent',
        'Grave Robber and Incandescent'
        -- 'These perks synchronize incredibly well with the Solar 3.0 rework in Season 17. All classes have powerful solar melees which can easily achieve a final blow to reload with Grave Robber. Incandescent can synchronize with fragments such as Ember of Searing and Ember of Singeing, and has a generous radius of effect.'
    ),(
        2,
        'Austringer',
        'https://ik.imagekit.io/kwroldan/Capstone/Austringer_W66yh0aKI.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654720693430',
        'Triple Tap',
        'Air Assault',
        'Snapshot Sights',
        'Compulsive Reloader',
        'Outlaw',
        'Eye of the Storm',
        'Demolitionist',
        'Zen Moment',
        'Rangefinder',
        'Rampage',
        'Frenzy',
        'Opening Shot',
        'Outlaw and Rampage'
        -- 'The classic wombo-combo. Rampage will increase our damage by up to 33%, and Outlaw boosts reload to ludicrous levels. Slap on Rampage Spec in the mod slot and those red-bars never stood a chance.'
    ),(
        3,
        'Drang (Baroque)',
        'https://ik.imagekit.io/kwroldan/Capstone/DrangBaroque_65q2KGDnH.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654791207068',
        'Moving Target',
        'Disruption Break',
        'Well Rounded',
        'Quickdraw',
        'Wellspring',
        'Eye of the Storm',
        'Vorpal Weapon',
        'Zen Moment',
        'Incadescent',
        'Turnabout',
        'Rampage',
        'Swashbuckler',
        'Wellspring and Incandescent'
        -- 'Ability-spam builds are some of the most fun playstyles in Destiny 2. Wellspring will help replenish all of your abilities on final blows. Incandescent can synchronize with fragments such as Ember of Searing and Ember of Singeing, and has a generous radius of effect. These traits combined can eliminate any down-time you have in your ability rotations.'
    ),(
        4,
        'Beloved',
        'https://ik.imagekit.io/kwroldan/Capstone/Beloved_lJ9BeNKaW.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654791297522',
        'Firmly Planted',
        'Compulsive Reloader',
        'Fourth Time''s the Charm',
        'No Distractions',
        'Surplus',
        'Snapshot Sights',
        'Turnabout',
        'Rampage',
        'Quickdraw',
        'Incandescent',
        'Box Breathing',
        'Moving Target',
        'Fourth Time''s the Charm and Incadescent'
        -- 'For PvE, Fourth Time''s the Charm will help bring down some of those beefier targets and maintain decent DPS and help with ammo economy. Incandescent ensures that when those targets are eliminated, some of that ammo spent will spread to damage enemies nearby. For PvP, it is difficult to beat Snapshot Sights and Moving Target.'
    ),(
        5,
        'Firefright',
        'https://ik.imagekit.io/kwroldan/Capstone/Firefright_9IMqVbCBA.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1655137613555',
        'Hip-fire Grip',
        'Threat Detector',
        'Air Assault',
        'Well Rounded',
        'Fourth Time''s the Charm',
        'Fragile Focus',
        'Surrounded',
        'Mulligan',
        'Elemental Capacitor',
        'Adagio',
        'Osmosis',
        'Focused Fury',
        'Fourth Time''s the Charm and Focused Fury'
        -- 'Focused Fury requires 50% of the magazine to be precision shots without reloading or stowing the weapon. Fourth Time''s the Charm allows you to get more rounds per magazine by hitting precision shots, so these synchronize nicely together to keep the onslaught going. Plus, a 20% damage increase without any kills required is strong even in endgame content such as Master content or Grandmaster content.'
    ),(
        6,
        'Without Remorse',
        'https://ik.imagekit.io/kwroldan/Capstone/WithoutRemorse_yNz5lZ2Aqw.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654795314254',
        'Hip-fire Grip',
        'Stats for All',
        'Threat Detector',
        'Field Prep',
        'Well Rounded',
        'Steady Hands',
        'Elemental Capacitor',
        'Fragile Focus',
        'Turnabout',
        'One-Two Punch',
        'Vorpal Weapon',
        'Incandescent',
        'Steady Hands and Incandescent'
        -- 'Steady Hands is underappreciated. The handling bonus applies to all of your weapons, not just the weapon with the perk. This can make very potent combos with quickswapping much easier. Incandescent can synchronize with fragments such as Ember of Searing and Ember of Singeing, and has a generous radius of effect. These perks combined can allow you to get into the fray and recharge your abilities quickly.'
    ),(
        7,
        'Hollow Denial',
        'https://ik.imagekit.io/kwroldan/Capstone/HollowDenial_I7J7ezhE7q.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654720693686',
        'Rangefinder',
        'Well Rounded',
        'Surplus',
        'Heating Up',
        'Lead from Gold',
        'Adaptive Munitions',
        'Dragonfly',
        'Wellspring',
        'Unrelenting',
        'Swashbuckler',
        'Repulsor Brace',
        'Killing Tally',
        'Lead from Gold and Killing Tally'
        -- 'Lead from Gold allows you to run finders for your heavy weapon in your helmet mods while still allowing generous amounts of ammo to go to your special weapon. Killing Tally is extremely potent with a 30% damage increase that stays as long as you don''t reload or stow the weapon. Combining these perks keeps the ammo coming and the damage going.'
    ),(
        8,
        'Tears of Contrition',
        'https://ik.imagekit.io/kwroldan/Capstone/TearsOfContrition_7o0Pu8nzk2.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654790635925',
        'Perpetual Motion',
        'Auto-loading Holster',
        'Well Rounded',
        'No Distractions',
        'Triple Tap',
        'Compulsive Reloader',
        'Opening Shot',
        'Mulligan',
        'Vorpal Weapon',
        'Explosive Payload',
        'Fourth Time''s the Charm',
        'Focused Fury',
        'Triple Tap and Explosive Payload'
        -- 'These two perks are the standard combination for endgame content, such as Master or Grandmaster. The beefier targets require more damage to take down, so Triple Tap will extend your magazine. Explosive Payload adds damage to your weapon and has no damage falloff, increasing the effective range of your weapon.'
    ),(
        9,
        'Nezarac''s Whisper',
        'https://ik.imagekit.io/kwroldan/Capstone/NazeracsWhisper_SOoGWcRAK.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654790712836',
        'Lead from Gold',
        'Tilting at Windmills',
        'Genesis',
        'Compulsive Reloader',
        'Impulse Amplifier',
        'Demolitionist',
        'Adrenaline Junkie',
        'Turnabout',
        'Adaptive Munitions',
        'Frenzy',
        'Vorpal Weapon',
        'Unstoppable Force',
        'Impulse Amplifier and Frenzy'
        -- 'Glaives fundamentally require their shots to land to keep the gameplay loop going. Shots replenish shields, shields help close the gap, melees can chop enemies up pretty quickly. With this in mind, we want to reduce the amount of time we spend outisde of that loop. Impulse Amplifier makes it easier to land our shots and boosts our reload, while Frenzy will increase our damage and further boost our reload.'
    ),(
        10,
        'Bump in the Night',
        'https://ik.imagekit.io/kwroldan/Capstone/BumpInTheNight_BiBfwh1Tk.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654792166096',
        'Steady Hands',
        'Stats for All',
        'Demolitionist',
        'Tracking Module',
        'Field Prep',
        'Autoloading Holster',
        'Chill Clip',
        'Unrelenting',
        'Frenzy',
        'Chain Reaction',
        'Turnabout',
        'Vorpal Weapon',
        'Autoloading Holster and Frenzy'
        -- 'Autoloading Holster allows for a lot of versatility in the use of rocket launchers. Whether you''re hotswapping with Izanagi''s Burden, or you''re trying to put down as much burst DPS as possible, Autoloading Holster helps by eliminating the need for a reload. Frenzy is preferred over Vorpal Weapon due to increased damage Frenzy provides, as well as the other benefits.'
    ),(
        11,
        'Lingering Dread',
        'https://ik.imagekit.io/kwroldan/Capstone/LingeringDread_Qs3qI5BgS.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654720693202',
        'Autoloading Holster',
        'Ambitious Assassin',
        'Unrelenting',
        'Well Rounded',
        'Steady Hands',
        'Feeding Frenzy',
        'Chill Clip',
        'Demolitionist',
        'Vorpal Weapon',
        'Danger Zone',
        'Multikill Clip',
        'Harmony',
        'Autoloading Holster and Harmony'
        -- 'This combination supports any Energy Primary weapon splendidly. Autoloading Holster eliminates the reloading process, which can be painful on breech-loaded grenade launchers. Harmony gives a generous 20% damage buff if you score a final blow with another weapon. This allows you to clear some red-bars and pump out good damage on beefier targets while Harmony is active.' 
    ),(
        12,
        'New Purpose',
        'https://ik.imagekit.io/kwroldan/Capstone/NewPurpose_lgTfLaCSA.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654793026253',
        'Perpetual Motion',
        'Feeding Frenzy',
        'Well Rounded',
        'Heating Up',
        'Steady Hands',
        'Tunnel Vision',
        'Desperado',
        'Headstone',
        'Vorpal Weapon',
        'Harmony',
        'Focused Fury',
        'Adaptive Munitions',
        'Perpetual Motion and Adaptive Munitions'
        -- 'High-Impact Frames such as this inherently have poor handling, and Perpetual Motion will boost handling (as well as reload and stability). This is the first Kinetic primary weapon that has Adaptive Munitions which helps tremendously in Master and Grandmaster content, or anywhere Match Game is a modifier.'
    ),(
        13,
        'Unforgiven',
        'https://ik.imagekit.io/kwroldan/Capstone/Unforgiven_k7CVi8Xzf.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654793026159',
        'Well Rounded',
        'Demolitionist',
        'Feeding Frenzy',
        'Steady Hands',
        'Tunnel Vision',
        'Fragile Focus',
        'Adrenaline Junkie',
        'Frenzy',
        'Dragonfly',
        'Golden Tricorn',
        'Rampage',
        'Repulsor Brace',
        'Demolitionist and Golden Tricorn'
        -- 'Demolitionist and Golden Tricorn are a powerful combination. Demolitionist will replenish grenade energy with final blows, and Golden Tricorn gives a hefty 50% damage increase if you get a final blow with a grenade. These perks keep a non-stop chain of huge damage going. Especially potent if using Echo of Undermining on Void.'
    ),(
        14,
        'Stormchaser',
        'https://ik.imagekit.io/kwroldan/Capstone/Stormchaser_b8ha5WBBM.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654793026186',
        'Rapid Hit',
        'Clown Cartridge',
        'Auto-loading Holster',
        'Rangefinder',
        'Well Rounded',
        'Turnabout',
        'Vorpal Weapon',
        'Firing Line',
        'Frenzy',
        'Demolitionist',
        'Adaptive Munitions',
        'Rampage',
        'Clown Cartridge and Firing Line'
        -- 'The Holy Mecca of DPS. Clown Cartridge increases the number of rounds you can fire in one magazine, and Firing Line gives a 20% boost to precision damage for free (as long as you have two allies nearby). In group activities, it''s difficult to beat this potent combination.'
    ),(
        15,
        'The Epicurean',
        'https://ik.imagekit.io/kwroldan/Capstone/Epicurean_7dBjRN47j.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654793026148',
        'Ensemble',
        'Feeding Frenzy',
        'Well Rounded',
        'Snapshot Sights',
        'Quickdraw',
        'Surplus',
        'Cornered',
        'Moving Target',
        'Rangefinder',
        'Backup Plan',
        'Swashbuckler',
        'Repulsor Brace',
        'Feeding Frenzy and Swashbuckler'
        -- 'Swashbuckler allows for an instant 33% damage increase if you get a melee final blow, and from there you can chain kills nicely with minimal downtime thanks to Feeding Frenzy boosting reload speed.'
    ),(
        16,
        'Fixed Odds',
        'https://ik.imagekit.io/kwroldan/Capstone/FixedOdds_QG_exnJzUg.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1654793026324',
        'Quickdraw',
        'No Distractions',
        'Encore',
        'Field Prep',
        'Feeding Frenzy',
        'Under Pressure',
        'Incandescent',
        'Focused Fury',
        'Firing Line',
        'Rangefinder',
        'Rampage',
        'Killing Tally',
        'Field Prep and Killing Tally'
        -- 'Killing Tally is an extremely potent damage bonus, providing up to 30% bonus damage in perpetuity, until the weapon is stowed or reloaded. Field Prep increases maximum ammo capacity, allowing for more carnage in total. Additionally, when a reload is needed, crouching before reloading will massively increase the speed at which we reload, thanks again to Field Prep.'
);